"use strict";
import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#fff",
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 20,
    color: "#000",
  },

  button: {
    fontSize: 12,
    color: "#000",
    backgroundColor: "#fff",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    zIndex: 2,
    // borderColor: 'red',
    paddingVertical: 20,
  },
  modalView: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 35,
    width: "90%",
    textAlign: "center",
    // alignItems: 'center',
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 1,
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
    color: "#080808",
    fontSize: 18,
    fontFamily: "Roboto-Regular",
  },
  textStyle: {
    color: "white",
    fontFamily: "Roboto-Bold",
    textAlign: "center",
  },
  formBox: {
    marginHorizontal: 20,
  },
  iconBox: {
    width: 40,
    height: 40,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  inputGroup: {
    height: 54,
    fontSize: 16,
    fontFamily: "Roboto-Regular",
    color: "#000",
    width: "75%",
  },
  clearFeild: {
    height: 55,
    width: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  btnWrap: {
    paddingHorizontal: 20,
  },
  primaryBtn: {
    backgroundColor: "#EA5242",
    minHeight: 50,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    textAlign: "center",
    flex: 1,
  },
  lightBgBtn: {
    backgroundColor: "#D9D9D9",
    minHeight: 50,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    flex: 1,
  },
  primaryBtnTxt: {
    color: "#fff",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
  },
  lightBgBtnTxt: {
    color: "#aaaaaa",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
  },
  createAcTxt: {
    marginTop: 10,
    textAlign: "center",
    color: "#080808",
    fontSize: 14,
    textDecorationLine: "underline",
    fontFamily: "Roboto-Regular",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    zIndex: 2,
    // borderColor: 'red',
    paddingVertical: 20,
  },
  modalSingleTxt: {
    marginBottom: 20,
    textAlign: "center",
    color: "#080808",
    fontSize: 15,
    fontFamily: "Roboto-Regular",
  },
  logoTagline: {
    // paddingTop: 20,
    marginTop: 23,
    marginBottom: 8,
    fontSize: 16,
    fontFamily: "Roboto-Medium",
    fontStyle: "normal",
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: "center",
    color: "#080808",
    minHeight: 20,
  },
  taglineTxt: {
    color: "#888989",
    // width: 275,
    lineHeight: 18,
    fontSize: 14,
    fontFamily: "Roboto-Regular",
    textAlign: "center",
    marginHorizontal: 25,
    marginBottom: 20,
  },
  errorTxt: {
    paddingLeft: 10,
    fontFamily: "Roboto-Regular",
    fontSize: 12,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: "left",
    color: "#ea5242",
    marginVertical: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    zIndex: 2,
    // borderColor: 'red',
    paddingVertical: 20,
  },
  primaryTxt: {
    color: "#EA5242",
    fontSize: 12,
    fontFamily: "Roboto-Regular",
  },
});
